

# FILE
FILE_PATH = "stats.xlsx"
FILE_SHEET = "LAA"
# FILE_SHEET = "TEX"

FILE_ENGINE = "openpyxl"

TEAMS = ["Los Angeles Angels", "A's Oakland"]
# Contact_ability
CONTACT_ABILITY_AVG_SCORE = 60
CONTACT_ABILITY_CLT_SCORE = 5
CONTACT_ABILITY_VISION_SCORE = 25
CONTACT_ABILITY_DISC_SCORE = 10
 
# Abilities
MAIN_SCORE = 70
SUB_SCORE = 30

# - - -- - - - arqtype scores required - - - -- - 

# Contact hitter (Leadoff)
CONTACT_HITTER_C_AB_REQUIRED = 55
CONTACT_HITTER_BS_AB_REQUIRED = 25 
CONTACT_HITTER_BAT_AB_REQUIRED = 15

# Powerhouse
POWERHOUSE_POWER_REQUIRED = 65  
POWERHOUSE_CLT_REQUIRED = 20    
POWERHOUSE__CONTACT_REQUIRED = 10
POWERHOUSE_VISION_REQUIRED = 5

# Fundamental
FUNDAMENTAL_VISION_REQUIRED = 30   
FUNDAMENTAL_CLT_REQUIRED = 25
FUNDAMENTAL_DISCIPLINE_REQUIRED = 25 
FUNDAMENTAL_CONTACT_REQUIRED = 20

# offroad
OFFROAD_CONTACT_REQUIRED = 30
OFFROAD_POWER_REQUIRED = 34    
OFFROAD_SPEED_REQUIRED = 4
OFFROAD_CLT_REQUIRED = 32

# 
